# Site settings
title: Ulrich Dobramysl
email: ulrich.dobramysl@gmail.com
description:
baseurl: ""
url: "http://127.0.0.1:4000"
twitter_username: ulidobra
github_username:  ulido

# Build settings
markdown: kramdown
